### ISSUE TITLE
the original WSI data

### ISSUE THREAD

**Issue by mk-runner** [dddavid4real/HistGen#1]
Well done, can you provide the original WSI data? Thank you!

**Comment by dddavid4real** [comment]
Hi! We are still organizing the data and the upload may take some time since there are over 7,000 slides. There are several solutions if you want to reproduce our method as soon as possible:
1. download the WSIs from TCGA directly by using the Case IDs provided in the annotation.json file (already uploaded)
2. use our provided DINOv2 features of these WSIs for preliminary experiments

**Comment by dddavid4real** [comment]
Hi,

Since the total file size of original WSIs is too large (~7T) and we haven't managed to find an online server to upload and save them efficiently, we recommend to download directly from TCGA Data Portal using the case ids provided in our annotation.json file.

This issue will be closed. Feel free to re-open it if you have further questions.
