### ISSUE TITLE
Purpose of visual encoder and visualisation of report phrases

### ISSUE THREAD

**Issue by BenPashley** [dddavid4real/HistGen#11]
Hello again,

Making good progress with replicating your results :)  Could you just clarify a few points?

What is the purpose of the visual encoder considering you are already using dinov2l for feature extraction from the patches?

Do you have a method within your current framework to generate heatmaps to visualisation words and phrases (similar to the HistoGPT library)?

Lastly, I'm very keen to evaluate cancer sub-typing using your method.  Would you mind sharing your adapted code?

**Comment by dddavid4real** [comment]
Hi, we assume that DINOv2 provides good enough **initial** features. Yet for report generation, more delicately designed visual encoding procedure is needed. That's why we proposed the hierarchical visual encoding module to learn the features of WSI in both fine- and coarse-grained ways.

For your second question, sorry we did not include the codes you described.

And for the subtyping and survival analysis codes, we might re-organize and upload them after November since there are several deadlines and projects on hand. Sorry for the inconvenience.
