### ISSUE TITLE
Asking about When HistGen Will Be Integrated into EasyMIL

### ISSUE THREAD

**Issue by blz822** [dddavid4real/HistGen#16]
Dear author,
I'm really interested in your work and noticed that you mentioned you are currently organizing the pre-trained checkpoints and merging HistGen into EasyMIL. I'm wondering if you could share an approximate timeline for when this integration will be completed? I'm looking forward to the updated version.
Thank you very much!

**Comment by dddavid4real** [comment]
Hi,

Thank you for your interest. An estimated time for releasing the code of HistGen for downstream tasks would be mid/late December since we currently have several near deadlines on hand. 

By the way, you could try to merge the visual encoder part of HistGen to CLAM repo, serving as one of those MIL models.

Thank you for your patience.
