### ISSUE TITLE
Original WSI data 

### ISSUE THREAD

**Issue by Andyfever123** [dddavid4real/HistGen#2]
Sorry to interrupt, but your work is very innovative and provides a new dataset and report generation method for that dataset to the field of medical report generation. Can you make your WSI dataset public? Or be able to show a few images first to see what they look like. Thank you very much for your hard work!

**Comment by dddavid4real** [comment]
Hello. Since the original WSI data are very large and take around 7T space, we are trying to organize them and find an online platform to upload them. A better way is to directly download them from the [TCGA data portal](https://portal.gdc.cancer.gov/analysis_page?app=Downloads). Meanwhile, the feature files we provided are ready to be downloaded, and you can use these files to reproduce our experiments (which does not need the original WSI files).
