### ISSUE TITLE
Clarification on max_seq_length and Benchmark Evaluation in Table 1

### ISSUE THREAD

**Issue by casperliuliuliu** [dddavid4real/HistGen#20]
Hi, 

I would like to clarify a couple of points regarding the implementation and evaluation in your paper:

1. While reading through your code, I noticed that the `max_seq_length` is set to 100 for both training and testing data. Is the benchmark reported in **Table 1** of your paper evaluated using only the first 100 tokens of the medical report? If so, could you elaborate on why this specific length was chosen?

2. Additionally, I see that you recently updated a new cleaned annotation file. Could you confirm whether the benchmark in Table 1 was evaluated using the first 100 tokens from `annotations712_update.json`, or does it use the first 100 tokens from the older `annotation.json` file?

Thank you for clarifying these details!

**Comment by dddavid4real** [comment]
Hi,

1. Yes, we follow the practical settings of most report generation papers and set the max_seq_length to 100. And during inference, we find that this setting is enough to decode all contents of most reports.
2. The benchmark in Table 1 is based on the original annotation.json file. So the results might be a little different for HistGen and other baselines since we updated the annotations files and tokenizer for better decoding performance.

**Comment by casperliuliuliu** [comment]
Thank you for your response and clarification!
